services:
  siren:
    container_name: siren
    restart: unless-stopped
    image: eclipse-mosquitto:latest
    ports:
      - 1883:1883
      - 9002:9001 # win conflict on 9001
    expose:
      - 1883
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    cpu_shares: 2048
    oom_kill_disable: true
