services:
    scylla-server:
        depends_on:
            - siren
        environment:
            - SCYLLA_SIREN_HOST_URL=siren:1883
            - SCYLLA_BATCH_UPSERT_TIME=20
        init: false

    client:
      extends:
        file: ../angular-client/compose.client.yml
        service: client

    siren:
        extends:
            file: ../siren-base/compose.siren.yml
            service: siren
