services:
    scylla-server:
        environment:
            - SCYLLA_SIREN_HOST_URL=siren:1883
            - SCYLLA_PROD=true

    siren:
        extends:
            file: ../siren-base/compose.siren.yml
            service: siren

    calypso:
        extends:
            file: ./compose.calypso.yml
            service: calypso
        depends_on:
            - siren
